services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=CHANGE_ME
    volumes:
      - postgres:/var/lib/postgresql/data

volumes:
  postgres:
